<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activate' => '激活',
    'Add' => '添加',
    'Admin' => '管理员',
    'Application' => '应用',
    'Are you sure to delete this item?' => '确认要删除吗?',
    'Are you sure you want to activate this user?' => '确认要激活此用户吗？',
    'Assign' => '分配',
    'Assignment' => '分配',
    'Assignments' => '分配',
    'Change' => '修改',
    'Change Password' => '修改密码',
    'Old Password' => '旧密码',
    'New Password' => '新密码',
    'Retype Password' => '重新输入新密码',
    'Incorrect Old Password' => '旧密码不正确',
    'Class Name' => '类名',
    'Create' => '新增',
    'Create Menu' => '新增菜单',
    'Create Rule' => '新增规则',
    'Data' => '数据',
    'Delete' => '删除',
    'Description' => '描述',
    'Help' => '帮助',
    'ID' => 'ID',
    'Login' => '登录',
    'Menus' => '菜单列表',
    'Name' => '名称',
    'Order' => '排序',
    'Parent' => '父级',
    'Parent Name' => '父级名称',
    'Remove' => '删除',
    'Reset' => '重置',
    'Route' => '路由',
    'Routes' => '路由列表',
    'Rule "{value}" does not exists' => '规则不存在',
    'Rule Name' => '规则名称',
    'Rules' => '规则列表',
    'Save' => '保存',
    'Search' => '查询',
    'Type' => '类型',
    'Update' => '更新',
    'Inactive' => '未激活',
    'Active' => '已激活',
    'Update Menu' => '更新菜单',
    'Update Rule' => '更新规则',
    'Username' => '用户名',
    'Email' => '邮箱地址',
    'Users' => '用户列表',
    'Created At' => '创建时间',
    'Status' => '状态',
    'Create User' => '创建用户',
    '\'{class}\' must extend from \'yii
bacRule\' or its child class' => '',
    'Create label' => '',
    'Invalid rule "{value}"' => '',
    'New route(s)' => '',
    'Search for assigned' => '',
    'Search for available' => '',
    'Send' => '',
    'Signup' => '',
    'Unknown class \'{class}\'' => '',
    'Update label' => '',
    'Append' => '@@追加@@',
    'Assigned' => '@@分配@@',
    'Available' => '@@可用@@',
    'Create Permission' => '@@新增权限@@',
    'Create Permissions' => '@@新增权限列表@@',
    'Create Role' => '@@创建角色@@',
    'Create route' => '@@新增路由@@',
    'Generate Routes' => '@@生成路由@@',
    'Menu' => '@@菜单@@',
    'New' => '@@新增@@',
    'Permission' => '@@权限@@',
    'Permissions' => '@@权限列表@@',
    'Role' => '@@角色@@',
    'Roles' => '@@角色列表@@',
    'Rule' => '@@规则@@',
    'Update Permission' => '@@更新权限@@',
    'Update Role' => '@@更新角色@@',
    'User' => '@@用户@@',
];
